### ISSUE TITLE
ERROR : category 'cookie-consent' 

### ISSUE THREAD

**Issue by ChrisWeit** [dmstr/yii2-cookie-consent#5]
Hi,
sorry to post this, but I just don't know what I have to do here.

I get:

> Unable to locate message source for category 'cookie-consent'.

as an error message.

Anyone an idea what I need to fix? 
(I just installed and copy pasted component, use ..., and widget)

Thanks.

**Comment by eluhr** [comment]
You need to add a i18n component to your app configuration

See: https://www.yiiframework.com/doc/guide/2.0/en/tutorial-i18n#2-configure-one-or-multiple-message-sources

The key (in the example above _app*_) could be either _*_ (wildcard for every category) or _cookie-consent_


Example for PhpMessageSource:
```php
...
'i18n' => [
    'translations' => [
        'cookie-consent' => [
            'class'          => \yii\i18n\PhpMessageSource::class,
            'basePath'       => '@app/messages' // base path of your message file
            'sourceLanguage' => 'en'
        ]
    ]
]
...
```
For further informations see docs: https://www.yiiframework.com/doc/api/2.0/yii-i18n-phpmessagesource

Example for DbMessageSource:
```php
...
'i18n' => [
    'translations' => [
        'cookie-consent' => [
            'class' => \yii\i18n\DbMessageSource::class,
            'sourceLanguage' => 'en'
        ]
    ]
]
...
```
For further informations see docs: https://www.yiiframework.com/doc/api/2.0/yii-i18n-dbmessagesource

@germanbisurgi We should to add this to the projects readme!

**Comment by ChrisWeit** [comment]
Thanks for the answer.
